apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: main-and-pingpong-apps-namespace
  name: main-application-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-application
  template:
    metadata:
      labels:
        app: main-application
    spec:
      containers:
        - name: main-application
          image: mickeckemi21/main-application:4.01
          env:
            - name: SERVICE_PING_URL
              value: "http://ping-pong-app-svc:8585"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: main-application-configmap
                  key: message
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /actuator/health/readiness
              port: 8080
