apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: main-and-pingpong-apps-namespace
  name: ping-pong-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      labels:
        app: ping-pong-app
    spec:
      containers:
        - name: ping-pong-app
          image: mickeckemi21/ping-pong-app:4.01
          env:
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASSWORD
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://postgres-svc:5432/pingpong"
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /actuator/health/readiness
              port: 8089
