apiVersion: v1
kind: Service
metadata:
  namespace: main-and-pingpong-apps-namespace
  name: ping-pong-app-svc
spec:
  type: LoadBalancer
  selector:
    app: ping-pong-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8089
