apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-todo-app
  template:
    metadata:
      labels:
        app: simple-todo-app
    spec:
      containers:
        - name: simple-todo-app
          image: mickeckemi21/simple-todo-app:1.02
