apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"simple-todo-app-broadcaster-dep","namespace":"simple-todo-app-namespace"},"spec":{"replicas":6,"selector":{"matchLabels":{"app":"simple-todo-app-broadcaster"}},"template":{"metadata":{"labels":{"app":"simple-todo-app-broadcaster"}},"spec":{"containers":[{"env":[{"name":"NATS_SERVER_URL","value":"nats://my-nats.default:4222"},{"name":"BOT_SECRET","valueFrom":{"secretKeyRef":{"key":"BOT_SECRET","name":"simple-todo-app-broadcaster-secret"}}}],"image":"mickeckemi21/simple-todo-app-broadcaster:4.06","name":"simple-todo-app-backend"}]}}}}
  generation: 1
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
            f:spec:
              f:containers:
                k:{"name":"simple-todo-app-backend"}:
                  .: {}
                  f:env:
                    .: {}
                    k:{"name":"BOT_SECRET"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:secretKeyRef:
                          .: {}
                          f:key: {}
                          f:name: {}
                    k:{"name":"NATS_SERVER_URL"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
      manager: kubectl.exe
      operation: Update
      time: "2021-12-06T16:33:15Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: k3s
      operation: Update
      time: "2021-12-06T16:40:18Z"
  name: simple-todo-app-broadcaster-dep
  namespace: simple-todo-app-namespace
  resourceVersion: "14350"
  uid: 6566f698-bb88-4c4a-9941-6d36efcdf6e2
spec:
  progressDeadlineSeconds: 600
  replicas: 6
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: simple-todo-app-broadcaster
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: simple-todo-app-broadcaster
    spec:
      containers:
        - env:
            - name: NATS_SERVER_URL
              value: nats://my-nats.default:4222
            - name: BOT_SECRET
              valueFrom:
                secretKeyRef:
                  key: BOT_SECRET
                  name: simple-todo-app-broadcaster-secret
          image: mickeckemi21/simple-todo-app-broadcaster:4.06
          imagePullPolicy: IfNotPresent
          name: simple-todo-app-backend
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 6
  conditions:
    - message: ReplicaSet "simple-todo-app-broadcaster-dep-554cbb79bc" has successfully
        progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
  observedGeneration: 1
  readyReplicas: 6
  replicas: 6
  updatedReplicas: 6
