apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: pingpong-app-namespace
  name: pingpong-app
spec:
  template:
    metadata:
      name: pingpong-app-v1
    spec:
      containers:
        - image: mickeckemi21/ping-pong-app:4.01
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASSWORD
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-svc:5432/pingpong"
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /actuator/health/readiness
