apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: simple-todo-app-namespace
  name: simple-todo-app-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-todo-app-backend
  template:
    metadata:
      labels:
        app: simple-todo-app-backend
    spec:
      containers:
        - name: simple-todo-app-backend
          image: mickeckemi21/simple-todo-app-backend:4.02
          env:
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: DB_PASSWORD
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://postgres-svc:5432/simpletodo"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
